name: Full Release

on:
  workflow_dispatch:
    branches: [main]
    inputs:
      release_type:
        description: 'The type of version bump (patch, minor, major)'
        required: false
        default: 'patch'
permissions:
  contents: write
  packages: write

jobs:
  release-cycle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
      - name: Bump package version
        id: bump_version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          new_version=$(npm version patch -m "chore(release): %s [skip ci]")
          echo "version=$new_version" >> "$GITHUB_OUTPUT"
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.version }}
          name: ${{ steps.bump_version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
