name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    concurrency:
      group: 'full-release-${{ github.ref }}'
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Bump package version
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release_type || 'patch' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [[ "$RELEASE_TYPE" != "patch" && "$RELEASE_TYPE" != "minor" && "$RELEASE_TYPE" != "major" ]]; then
            echo "Error: Invalid RELEASE_TYPE '$RELEASE_TYPE'. Allowed values are 'patch', 'minor', 'major'." >&2
            exit 1
          fi
          npm version "$RELEASE_TYPE" -m "chore(release): %s [skip ci]"
          git push --follow-tags
